<a href="https://colab.research.google.com/github/RyanAugustyn/Pytorch-Intro/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Course github discussion: https://github.com/mrdbourke/pytorch-deep-learning/discussions



Changed the above to text cell by highlighting and hitting ctrl + mm



Hit shift + enter to start a new code cell while typing, or if not in a cell hit ctrl + mb

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
# Introduction to Tensors-Creating tensors

#torch.tensor documentation at https://pytorch.org/docs/stable/tensors.html
#encodes into 'tensor' data type

#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
#has no dimensions
scalar.ndim

scalar2 = torch.tensor([[1,2], [3,4]])
scalar2

#tried running with different lengths, produced error when scalars not equal size
scalar3 = torch.tensor([[1,2,2,2], [3,4,5,5], [6,7,8,9]])
scalar3


tensor([[1, 2, 2, 2],
        [3, 4, 5, 5],
        [6, 7, 8, 9]])

In [4]:
scalar2.ndim

2

In [5]:
scalar3.ndim

2

In [6]:
#get tensor back as Python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#dimension correspond to number of square brackets (number of pairs of closing square brackets)
#but shape of above vector is 2

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [3,6,9],[2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape
#below means 'have a single 3x3 shape tensor
#can think of as corresponding to each bracket in above tensor output

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
#TENSOR[1] -error, out of bounds ie only 1 dimension

In [20]:
#tensor practice
#tried copy/pasting same brackets as TENSOR twice, got error of 'takes 1
#positional argument but two were given'...ie torch.tensor takes online 1 input
# TENSOR1 = torch.tensor([[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]], [[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]])
# TENSOR1

TENSOR1 = torch.tensor([[[[1,2], [3,4], [5,6], [7,8]]]])
TENSOR1

tensor([[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]])

In [21]:
TENSOR1.ndim

4

In [22]:
TENSOR1.shape

torch.Size([1, 1, 4, 2])

In [23]:
TENSOR2 = torch.tensor([[[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]],[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]]])
TENSOR2.ndim

5

In [24]:
TENSOR2.shape
#you can move along each bracket and count # of instances in each bracket

torch.Size([1, 1, 2, 4, 2])

In [25]:
#note scalars and vectors by convention use lowercase, while matix/tensor use upper

### Random Tensors

Why random tensors?

Important because the way many neural networks learn is they start with tensors full of random numbers, and then adjust those random numbers to better represent the data

So...start random numbers, check with data, update random numbers, repeat

Documentation: https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.5058, 0.9370, 0.0995, 0.0860],
        [0.1948, 0.9889, 0.2772, 0.8113],
        [0.3596, 0.5638, 0.8835, 0.6276]])

In [27]:
random_tensor.ndim

2

In [28]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.2757, 0.8871, 0.4456, 0.9749],
         [0.3533, 0.2218, 0.2288, 0.9857],
         [0.6551, 0.5215, 0.6481, 0.3066]]])

In [30]:
#create random tensor with similar shape to an image tensor
#as seen here, almost anything can be represented as data
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
another_rand_tensor = torch.rand(3, 5, 5)
another_rand_tensor

tensor([[[0.7278, 0.9654, 0.5473, 0.2508, 0.5862],
         [0.7019, 0.9107, 0.8604, 0.9899, 0.3342],
         [0.7574, 0.9355, 0.4136, 0.3081, 0.5663],
         [0.5614, 0.0642, 0.7894, 0.1924, 0.3779],
         [0.8494, 0.4046, 0.6765, 0.2551, 0.7440]],

        [[0.1037, 0.8462, 0.2826, 0.2208, 0.3416],
         [0.3471, 0.9162, 0.0772, 0.6574, 0.7440],
         [0.4950, 0.7115, 0.1826, 0.2213, 0.9261],
         [0.2689, 0.5259, 0.2035, 0.6389, 0.3648],
         [0.0725, 0.7099, 0.6823, 0.3321, 0.5086]],

        [[0.7631, 0.4653, 0.5678, 0.5946, 0.3119],
         [0.0361, 0.7696, 0.0587, 0.1091, 0.6169],
         [0.1447, 0.0775, 0.6465, 0.5872, 0.4648],
         [0.1733, 0.9845, 0.2758, 0.8623, 0.9370],
         [0.2012, 0.3585, 0.1845, 0.3943, 0.6942]]])

In [32]:
#can also explicitely use the 'size' parameter
# ex = torch.rand(size =(3, 3))
# ex

###Zeroes and ones

In [33]:
#Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
#If want to zero all numbers out in a tensor
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
#Default data type of tensor
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [37]:
#Torch.range() is not recommended due to inconsistent behavior,
#torch.range(0, 10)

In [38]:
#torch.arrange() is preferred
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#note the ending number is not inclusive
arange_ex = torch.arange(start=0, end=1000, step=77)
arange_ex

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
#Creating tensors like (in the same shape as)
one_to_ten = torch.arange(0, 10)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
X = torch.arange(3, 42, 7)
Y = torch.zeros_like(X)
Y

tensor([0, 0, 0, 0, 0, 0])



```
# This is formatted as code
```

###Tensor datatypes

**Note:** Tensor datatypes is one fo the 3 big errors with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [42]:
#Float 32 tensor
#If trying to set default type as None, still set as torch.float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #what datatype is the tensor
                               device=None, # What device is your tensor on -'cuda' or 'cpu'-if try to do something with tensors on different devices, will produce error
                               requires_grad=False) # If want PyTorch to track gradients when tensors go through certain calculations
float_32_tensor


tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
#Runs fine, be aware of unexpected behavior though with different dtypes
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors


1. Tensors not right datatype- get datatype from a tensor, use `tensor.dtype`
2. Tensors not right shape-to get shape use `tensor.shape`
3. Tensors not on the right device- to get device, use `tensor.device`

NOTE: tensor.shape and tensor.size() can be used interchangably

In [48]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8311, 0.4582, 0.1527, 0.0654],
        [0.5195, 0.1430, 0.9301, 0.4634],
        [0.4663, 0.1868, 0.2292, 0.4399]])

In [49]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.8311, 0.4582, 0.1527, 0.0654],
        [0.5195, 0.1430, 0.9301, 0.4634],
        [0.4663, 0.1868, 0.2292, 0.4399]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors (tensor operations)

Tensor operations include:
*Addition
*Subtraction
*Multiplication (element-wise)
*Division
*Matrix multiplication

In [50]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [51]:
#Multiply
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [52]:
#Subtract
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [53]:
#Try out PyTorch in-built functions
#Generally use basic methods, easier to read
torch.mul(tensor, 10)


tensor([10, 20, 30])

#Matrix multiplication-number of columns of 1st matrix must match number of rows of 2nd

Or multiplying an MxN by an NxP matrix (Ns are the same) you get MxP

Multiplying a 1x3 by a 3x1 results in 1x1
But a 3x1 by a 1x3 results in a 3x3


###Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)

Reference: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2,2)`
* `(3, 2) @ (2, 3)` -> `(3,3)`


Visualization resource: http://matrixmultiplication.xyz/


In [54]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: ignored

In [ ]:
#Element wise multiplication
tensor * tensor
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

In [ ]:
#Matrix multiplication
# The @ symbol can also be substituted (tensor @ tensor) but matmul is clearer
torch.matmul(tensor, tensor)

In [ ]:
#Matrix multiplcation by hand
1*1 + 2*2 + 3*3

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

In [ ]:
%%time
torch.matmul(tensor, tensor)

In [ ]:
#Notice how matmul is much faster

###One of the most common erros in deep learning is shape errors

In [ ]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm is same as torch.matmul
torch.mm(tensor_A, tensor_B) #doesn't work now


To fix tensor shape issues, we can manipulate shape of our tensors using a **transpose**
A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
#The matrix multiplication oepration works when tensor_B is transposed
print(f"Originial shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")



In [ ]:
torch.matmul(tensor_A.T, tensor_B)

##Finding the min, max, mean, sum, etc (tensor aggregation)

In [55]:
#Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [59]:
#Find themax
torch.max(x), x.max()

(tensor(90), tensor(90))

In [61]:
#Find the mean
#torch.mean(x) will not work because wrong type
#Input should be float32 or complex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [65]:
#Find index of the min
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [66]:
#Find index of the max
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))