<a href="https://colab.research.google.com/github/RyanAugustyn/Pytorch-Intro/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Course github discussion: https://github.com/mrdbourke/pytorch-deep-learning/discussions



Changed the above to text cell by highlighting and hitting ctrl + mm



Hit shift + enter to start a new code cell while typing, or if not in a cell hit ctrl + mb

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
# Introduction to Tensors-Creating tensors

#torch.tensor documentation at https://pytorch.org/docs/stable/tensors.html
#encodes into 'tensor' data type

#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
#has no dimensions
scalar.ndim

scalar2 = torch.tensor([[1,2], [3,4]])
scalar2

#tried running with different lengths, produced error when scalars not equal size
scalar3 = torch.tensor([[1,2,2,2], [3,4,5,5], [6,7,8,9]])
scalar3


tensor([[1, 2, 2, 2],
        [3, 4, 5, 5],
        [6, 7, 8, 9]])

In [4]:
scalar2.ndim

2

In [5]:
scalar3.ndim

2

In [6]:
#get tensor back as Python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#dimension correspond to number of square brackets (number of pairs of closing square brackets)
#but shape of above vector is 2

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [3,6,9],[2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape
#below means 'have a single 3x3 shape tensor
#can think of as corresponding to each bracket in above tensor output

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
#TENSOR[1] -error, out of bounds ie only 1 dimension

In [20]:
#tensor practice
#tried copy/pasting same brackets as TENSOR twice, got error of 'takes 1
#positional argument but two were given'...ie torch.tensor takes online 1 input
# TENSOR1 = torch.tensor([[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]], [[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]])
# TENSOR1

TENSOR1 = torch.tensor([[[[1,2], [3,4], [5,6], [7,8]]]])
TENSOR1

tensor([[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]])

In [21]:
TENSOR1.ndim

4

In [22]:
TENSOR1.shape

torch.Size([1, 1, 4, 2])

In [23]:
TENSOR2 = torch.tensor([[[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]],[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]]])
TENSOR2.ndim

5

In [24]:
TENSOR2.shape
#you can move along each bracket and count # of instances in each bracket

torch.Size([1, 1, 2, 4, 2])

In [25]:
#note scalars and vectors by convention use lowercase, while matix/tensor use upper

### Random Tensors

Why random tensors?

Important because the way many neural networks learn is they start with tensors full of random numbers, and then adjust those random numbers to better represent the data

So...start random numbers, check with data, update random numbers, repeat

Documentation: https://pytorch.org/docs/stable/generated/torch.rand.html

In [27]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.9234, 0.4905, 0.1576, 0.6491],
        [0.1290, 0.4517, 0.1034, 0.3919],
        [0.2049, 0.7134, 0.3044, 0.0244]])

In [28]:
random_tensor.ndim

2

In [29]:
random_tensor.shape

torch.Size([3, 4])

In [31]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7581, 0.8114, 0.2406, 0.6087],
         [0.6729, 0.4492, 0.4394, 0.3094],
         [0.8549, 0.0815, 0.5884, 0.3329]]])

In [32]:
#create random tensor with similar shape to an image tensor
#as seen here, almost anything can be represented as data
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [33]:
another_rand_tensor = torch.rand(3, 5, 5)
another_rand_tensor

tensor([[[0.6235, 0.1493, 0.3564, 0.9696, 0.9870],
         [0.0842, 0.4305, 0.2072, 0.8154, 0.9479],
         [0.7976, 0.5892, 0.7012, 0.7261, 0.7175],
         [0.3227, 0.5857, 0.2626, 0.4806, 0.0562],
         [0.5562, 0.9375, 0.2182, 0.9184, 0.9237]],

        [[0.2952, 0.9851, 0.2124, 0.5424, 0.9654],
         [0.7258, 0.4825, 0.8887, 0.8981, 0.0306],
         [0.7798, 0.0581, 0.4572, 0.4017, 0.2135],
         [0.9462, 0.7871, 0.2621, 0.3571, 0.5109],
         [0.8664, 0.4679, 0.7064, 0.4339, 0.7573]],

        [[0.7440, 0.6907, 0.2008, 0.9234, 0.4807],
         [0.0365, 0.6811, 0.3917, 0.4914, 0.9286],
         [0.1200, 0.9268, 0.4173, 0.4943, 0.0488],
         [0.1593, 0.6827, 0.2347, 0.4321, 0.6118],
         [0.4037, 0.9454, 0.1621, 0.4402, 0.3000]]])