<a href="https://colab.research.google.com/github/RyanAugustyn/Pytorch-Intro/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Course github discussion: https://github.com/mrdbourke/pytorch-deep-learning/discussions



Changed the above to text cell by highlighting and hitting ctrl + mm



Hit shift + enter to start a new code cell while typing, or if not in a cell hit ctrl + mb

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
# Introduction to Tensors-Creating tensors

#torch.tensor documentation at https://pytorch.org/docs/stable/tensors.html
#encodes into 'tensor' data type

#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
#has no dimensions
scalar.ndim

scalar2 = torch.tensor([[1,2], [3,4]])
scalar2

#tried running with different lengths, produced error when scalars not equal size
scalar3 = torch.tensor([[1,2,2,2], [3,4,5,5], [6,7,8,9]])
scalar3


tensor([[1, 2, 2, 2],
        [3, 4, 5, 5],
        [6, 7, 8, 9]])

In [4]:
scalar2.ndim

2

In [5]:
scalar3.ndim

2

In [6]:
#get tensor back as Python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#dimension correspond to number of square brackets (number of pairs of closing square brackets)
#but shape of above vector is 2

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [3,6,9],[2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape
#below means 'have a single 3x3 shape tensor
#can think of as corresponding to each bracket in above tensor output

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
#TENSOR[1] -error, out of bounds ie only 1 dimension

In [20]:
#tensor practice
#tried copy/pasting same brackets as TENSOR twice, got error of 'takes 1
#positional argument but two were given'...ie torch.tensor takes online 1 input
# TENSOR1 = torch.tensor([[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]], [[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]])
# TENSOR1

TENSOR1 = torch.tensor([[[[1,2], [3,4], [5,6], [7,8]]]])
TENSOR1

tensor([[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]])

In [21]:
TENSOR1.ndim

4

In [22]:
TENSOR1.shape

torch.Size([1, 1, 4, 2])

In [23]:
TENSOR2 = torch.tensor([[[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]],[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]]])
TENSOR2.ndim

5

In [24]:
TENSOR2.shape
#you can move along each bracket and count # of instances in each bracket

torch.Size([1, 1, 2, 4, 2])

In [25]:
#note scalars and vectors by convention use lowercase, while matix/tensor use upper

### Random Tensors

Why random tensors?

Important because the way many neural networks learn is they start with tensors full of random numbers, and then adjust those random numbers to better represent the data

So...start random numbers, check with data, update random numbers, repeat

Documentation: https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.2365, 0.8419, 0.8273, 0.0970],
        [0.9150, 0.6489, 0.6520, 0.9124],
        [0.8278, 0.1297, 0.5965, 0.8723]])

In [27]:
random_tensor.ndim

2

In [28]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.1427, 0.0349, 0.2988, 0.7142],
         [0.4466, 0.1461, 0.2105, 0.5480],
         [0.2815, 0.0564, 0.4408, 0.4891]]])

In [30]:
#create random tensor with similar shape to an image tensor
#as seen here, almost anything can be represented as data
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
another_rand_tensor = torch.rand(3, 5, 5)
another_rand_tensor

tensor([[[7.8218e-01, 7.8953e-01, 4.6743e-01, 6.8300e-01, 1.7269e-01],
         [6.3917e-01, 3.1790e-01, 1.2245e-01, 3.8309e-01, 8.3428e-01],
         [1.1939e-01, 2.4469e-01, 5.1553e-01, 1.3368e-02, 2.8702e-01],
         [5.3263e-01, 7.0597e-01, 3.8443e-01, 6.3520e-01, 7.5750e-01],
         [9.7760e-01, 5.1734e-01, 4.6373e-01, 1.5357e-01, 8.7274e-01]],

        [[1.7995e-01, 3.4658e-01, 9.4266e-01, 2.6873e-01, 5.1817e-01],
         [8.8233e-01, 5.4159e-02, 6.5779e-01, 2.1640e-01, 1.7709e-01],
         [5.6948e-01, 5.6767e-01, 6.4765e-01, 3.4360e-01, 2.4588e-02],
         [7.2737e-02, 3.6985e-01, 8.9335e-01, 6.7664e-01, 7.2171e-01],
         [6.6032e-01, 5.2992e-01, 2.6655e-01, 3.7304e-01, 6.8704e-01]],

        [[2.5748e-01, 1.0543e-01, 7.8315e-01, 1.4400e-01, 7.4548e-01],
         [2.9376e-01, 7.9057e-01, 1.7829e-01, 2.2693e-01, 6.5873e-01],
         [4.6810e-01, 9.4720e-01, 4.2468e-01, 1.6958e-01, 2.3085e-01],
         [1.3187e-01, 8.4178e-01, 9.5020e-01, 6.5988e-01, 3.2212e-01],
  

In [32]:
#can also explicitely use the 'size' parameter
# ex = torch.rand(size =(3, 3))
# ex

###Zeroes and ones

In [33]:
#Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
#If want to zero all numbers out in a tensor
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
#Default data type of tensor
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [37]:
#Torch.range() is not recommended due to inconsistent behavior,
#torch.range(0, 10)

In [38]:
#torch.arrange() is preferred
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#note the ending number is not inclusive
arange_ex = torch.arange(start=0, end=1000, step=77)
arange_ex

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
#Creating tensors like (in the same shape as)
one_to_ten = torch.arange(0, 10)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
X = torch.arange(3, 42, 7)
Y = torch.zeros_like(X)
Y

tensor([0, 0, 0, 0, 0, 0])



```
# This is formatted as code
```

###Tensor datatypes

**Note:** Tensor datatypes is one fo the 3 big errors with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [42]:
#Float 32 tensor
#If trying to set default type as None, still set as torch.float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #what datatype is the tensor
                               device=None, # What device is your tensor on -'cuda' or 'cpu'-if try to do something with tensors on different devices, will produce error
                               requires_grad=False) # If want PyTorch to track gradients when tensors go through certain calculations
float_32_tensor


tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
#Runs fine, be aware of unexpected behavior though with different dtypes
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors


1. Tensors not right datatype- get datatype from a tensor, use `tensor.dtype`
2. Tensors not right shape-to get shape use `tensor.shape`
3. Tensors not on the right device- to get device, use `tensor.device`

NOTE: tensor.shape and tensor.size() can be used interchangably

In [48]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2057, 0.1400, 0.0190, 0.5767],
        [0.5179, 0.7654, 0.0031, 0.1333],
        [0.2830, 0.3205, 0.3822, 0.1178]])

In [49]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.2057, 0.1400, 0.0190, 0.5767],
        [0.5179, 0.7654, 0.0031, 0.1333],
        [0.2830, 0.3205, 0.3822, 0.1178]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
