<a href="https://colab.research.google.com/github/RyanAugustyn/Pytorch-Intro/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Course github discussion: https://github.com/mrdbourke/pytorch-deep-learning/discussions



Changed the above to text cell by highlighting and hitting ctrl + mm



Hit shift + enter to start a new code cell while typing, or if not in a cell hit ctrl + mb

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
# Introduction to Tensors-Creating tensors

#torch.tensor documentation at https://pytorch.org/docs/stable/tensors.html
#encodes into 'tensor' data type

#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
#has no dimensions
scalar.ndim

scalar2 = torch.tensor([[1,2], [3,4]])
scalar2

#tried running with different lengths, produced error when scalars not equal size
scalar3 = torch.tensor([[1,2,2,2], [3,4,5,5], [6,7,8,9]])
scalar3


tensor([[1, 2, 2, 2],
        [3, 4, 5, 5],
        [6, 7, 8, 9]])

In [4]:
scalar2.ndim

2

In [5]:
scalar3.ndim

2

In [6]:
#get tensor back as Python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#dimension correspond to number of square brackets (number of pairs of closing square brackets)
#but shape of above vector is 2

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [3,6,9],[2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape
#below means 'have a single 3x3 shape tensor
#can think of as corresponding to each bracket in above tensor output

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
#TENSOR[1] -error, out of bounds ie only 1 dimension

In [20]:
#tensor practice
#tried copy/pasting same brackets as TENSOR twice, got error of 'takes 1
#positional argument but two were given'...ie torch.tensor takes online 1 input
# TENSOR1 = torch.tensor([[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]], [[[1, 2, 3],
#          [3, 6, 9],
#          [2, 4, 5]]])
# TENSOR1

TENSOR1 = torch.tensor([[[[1,2], [3,4], [5,6], [7,8]]]])
TENSOR1

tensor([[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]])

In [21]:
TENSOR1.ndim

4

In [22]:
TENSOR1.shape

torch.Size([1, 1, 4, 2])

In [23]:
TENSOR2 = torch.tensor([[[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]],[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]]])
TENSOR2.ndim

5

In [24]:
TENSOR2.shape
#you can move along each bracket and count # of instances in each bracket

torch.Size([1, 1, 2, 4, 2])

In [25]:
#note scalars and vectors by convention use lowercase, while matix/tensor use upper

### Random Tensors

Why random tensors?

Important because the way many neural networks learn is they start with tensors full of random numbers, and then adjust those random numbers to better represent the data

So...start random numbers, check with data, update random numbers, repeat

Documentation: https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.8959, 0.8525, 0.7107, 0.7021],
        [0.3468, 0.6778, 0.3216, 0.6523],
        [0.6817, 0.6962, 0.4086, 0.5891]])

In [27]:
random_tensor.ndim

2

In [28]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.6919, 0.0565, 0.0475, 0.1971],
         [0.1898, 0.8055, 0.5160, 0.7149],
         [0.2981, 0.0514, 0.7573, 0.9917]]])

In [30]:
#create random tensor with similar shape to an image tensor
#as seen here, almost anything can be represented as data
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
another_rand_tensor = torch.rand(3, 5, 5)
another_rand_tensor

tensor([[[7.5935e-01, 5.8855e-01, 5.2425e-01, 1.2998e-01, 2.4971e-01],
         [4.9481e-01, 5.5965e-01, 5.1656e-01, 7.2046e-01, 6.6177e-01],
         [3.9143e-01, 5.6953e-01, 3.1377e-01, 3.3281e-01, 1.7256e-01],
         [3.3854e-01, 5.3694e-01, 2.1315e-01, 5.6167e-01, 1.3567e-01],
         [1.0121e-01, 9.9072e-01, 7.8160e-01, 8.1236e-01, 9.5784e-01]],

        [[8.7499e-01, 4.0443e-01, 8.5148e-01, 2.3918e-01, 3.3296e-01],
         [5.6823e-01, 3.4830e-01, 9.2122e-01, 2.7562e-01, 4.2590e-01],
         [2.3460e-01, 6.6535e-01, 3.9957e-01, 8.8900e-01, 6.8481e-01],
         [5.2529e-01, 4.2143e-03, 4.0860e-01, 3.0754e-01, 7.5885e-01],
         [7.6915e-01, 1.4647e-02, 2.8712e-01, 7.9497e-02, 2.8969e-01]],

        [[9.5066e-01, 4.8317e-01, 7.8771e-01, 9.0147e-01, 7.6134e-01],
         [5.0219e-02, 8.2337e-01, 4.7820e-01, 5.3270e-01, 3.6926e-01],
         [8.2455e-01, 6.6633e-01, 6.4474e-04, 7.7646e-01, 9.1140e-01],
         [4.4530e-01, 8.3644e-01, 2.1073e-01, 8.8089e-03, 8.7849e-01],
  

In [32]:
#can also explicitely use the 'size' parameter
# ex = torch.rand(size =(3, 3))
# ex

###Zeroes and ones

In [33]:
#Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
#If want to zero all numbers out in a tensor
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
#Default data type of tensor
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [37]:
#Torch.range() is not recommended due to inconsistent behavior,
#torch.range(0, 10)

In [38]:
#torch.arrange() is preferred
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#note the ending number is not inclusive
arange_ex = torch.arange(start=0, end=1000, step=77)
arange_ex

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
#Creating tensors like (in the same shape as)
one_to_ten = torch.arange(0, 10)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
X = torch.arange(3, 42, 7)
Y = torch.zeros_like(X)
Y

tensor([0, 0, 0, 0, 0, 0])



```
# This is formatted as code
```

###Tensor datatypes

**Note:** Tensor datatypes is one fo the 3 big errors with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [42]:
#Float 32 tensor
#If trying to set default type as None, still set as torch.float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #what datatype is the tensor
                               device=None, # What device is your tensor on -'cuda' or 'cpu'-if try to do something with tensors on different devices, will produce error
                               requires_grad=False) # If want PyTorch to track gradients when tensors go through certain calculations
float_32_tensor


tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
#Runs fine, be aware of unexpected behavior though with different dtypes
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors


1. Tensors not right datatype- get datatype from a tensor, use `tensor.dtype`
2. Tensors not right shape-to get shape use `tensor.shape`
3. Tensors not on the right device- to get device, use `tensor.device`

NOTE: tensor.shape and tensor.size() can be used interchangably

In [48]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7316, 0.5753, 0.4475, 0.3087],
        [0.6954, 0.3334, 0.8878, 0.6118],
        [0.1463, 0.1008, 0.3351, 0.7135]])

In [49]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.7316, 0.5753, 0.4475, 0.3087],
        [0.6954, 0.3334, 0.8878, 0.6118],
        [0.1463, 0.1008, 0.3351, 0.7135]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors (tensor operations)

Tensor operations include:
*Addition
*Subtraction
*Multiplication (element-wise)
*Division
*Matrix multiplication

In [50]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [51]:
#Multiply
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [52]:
#Subtract
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [53]:
#Try out PyTorch in-built functions
#Generally use basic methods, easier to read
torch.mul(tensor, 10)


tensor([10, 20, 30])

#Matrix multiplication-number of columns of 1st matrix must match number of rows of 2nd

Or multiplying an MxN by an NxP matrix (Ns are the same) you get MxP

Multiplying a 1x3 by a 3x1 results in 1x1
But a 3x1 by a 1x3 results in a 3x3


###Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)

Reference: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2,2)`
* `(3, 2) @ (2, 3)` -> `(3,3)`


Visualization resource: http://matrixmultiplication.xyz/


In [54]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: ignored

In [55]:
#Element wise multiplication
tensor * tensor
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [56]:
#Matrix multiplication
# The @ symbol can also be substituted (tensor @ tensor) but matmul is clearer
torch.matmul(tensor, tensor)

tensor(14)

In [57]:
#Matrix multiplcation by hand
1*1 + 2*2 + 3*3

14

In [58]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 957 µs, sys: 984 µs, total: 1.94 ms
Wall time: 1.69 ms


In [59]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 391 µs, sys: 56 µs, total: 447 µs
Wall time: 395 µs


tensor(14)

In [60]:
#Notice how matmul is much faster

###One of the most common erros in deep learning is shape errors

In [61]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm is same as torch.matmul
torch.mm(tensor_A, tensor_B) #doesn't work now


RuntimeError: ignored

To fix tensor shape issues, we can manipulate shape of our tensors using a **transpose**
A **transpose** switches the axes or dimensions of a given tensor.

In [62]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [63]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [64]:
#The matrix multiplication oepration works when tensor_B is transposed
print(f"Originial shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")



Originial shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [65]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

##Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
#Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [68]:
#Find themax
torch.max(x), x.max()

(tensor(90), tensor(90))

In [69]:
#Find the mean
#torch.mean(x) will not work because wrong type
#Input should be float32 or complex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [70]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [71]:
#Find index of the min
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [72]:
#Find index of the max
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View -return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with demensions permuted(swapped) in a certain way


In [73]:
#Create a tensor
#reimporting torch to only after to run from here on out after restart
import torch
x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
#Add an extra dimension
#Note: dimensions must be compatible with original dimensions
#so (1,7) is too small and (2,9) is trying to double
#number of elements without doubling the elements, both would both throw errors
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [75]:
#Change the view
#A different view of x
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
#Changing z changes x(because a view of a tensor shares the same memory as the
# original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [77]:
#Stack tensors on top of each other
#Can't use dim >= 2 as original tensor could only go to 1 dimension
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [78]:
# Vstack stacks tensors in sequence vertically(row wise)
#torch.vstack([x, z])
# Hstack stacks horizontally (column wise)
#torch.hstack([x, z])

In [79]:
#torch.squeeze removes a dimension
torch.squeeze(x_stacked, dim=-2)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [80]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [81]:
x_reshaped.squeeze()


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [82]:
x_reshaped.squeeze().shape

torch.Size([9])

In [83]:
#torch.unsqueeze adds a dimension
torch.unsqueeze (x_stacked, dim=1)

tensor([[[5., 5., 5., 5.]],

        [[2., 2., 2., 2.]],

        [[3., 3., 3., 3.]],

        [[4., 4., 4., 4.]],

        [[5., 5., 5., 5.]],

        [[6., 6., 6., 6.]],

        [[7., 7., 7., 7.]],

        [[8., 8., 8., 8.]],

        [[9., 9., 9., 9.]]])

In [84]:
#torch.unsqueeze() - adds a single dimension to a target tensor
# at a specific dim(dimension)
print(f"Previous target {x_squeezed}")
print(f"Previous shape {x_squeezed.shape}")

#Add extra dimension on zero dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [85]:
#torch.permute - rearranges the dimensions of a target tensor
# in a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, color_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

#Remember, permuted shares same place in memory
#Same data in both tensors
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [86]:
x_original[0, 0, 0] = 123
x_original[0, 0, 0]

tensor(123.)

In [87]:
x_permuted[0, 0, 0]

tensor(123.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [1]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
#Inexing on new tensor
#Index on outer bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
#Index on middle bracket (dim=1)
#Could also do x[0,0]
x[0][0]

tensor([1, 2, 3])

In [9]:
#index on most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [5]:
#indexing to number 9
x[0][2][2]

tensor(9)

In [6]:
#You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [7]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [8]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [10]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, : ]

tensor([1, 2, 3])

In [11]:
#Index to return, 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [12]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [13]:
array.dtype

dtype('float64')

In [14]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [17]:
#So be aware because numpy dtype is float 64, converting will not do default
#PyTorch datatype, would need to convert such as:
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [18]:
#Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [19]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
#Note original dtype is reflected when converted this way as well
#Change the tensor, what happens to `numpy_tensor`?
#Again, they don't share memory
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))